config/routes.rb
scope '(projects/:project_id)' do
  resources :easy_web_hooks, :except => [:show]
end

app/models/easy_web_hook.rb
class EasyWebHook < ActiveRecord::Base
  include Redmine::SafeAttributes

  ENTITY_TYPES = %w(Issue Project TimeEntry User)
  ENTITY_ACTIONS = %w(create update destroy)
  ENTITY_DATA_TYPES = %w(json xml)

  belongs_to :project
  belongs_to :author, :class_name => 'User'

  enum :status => { :active => 1, :inactive => 0 }

  validates :name, :entity_type, :action, :url, :author, :presence => true
  validates :action, :inclusion => { :in => ENTITY_ACTIONS }
  validates :entity_data_type, :inclusion => { :in => ENTITY_DATA_TYPES }
  validates :url, :format => { :with => URI.regexp }, :if => Proc.new {|hook| hook.url.present? }
  validate :validate_author_with_permission

  before_save :ensure_attributes

  safe_attributes 'name', 'entity_type', 'action', 'url', 'entity_data_type',
                  'project_id', 'author_id', 'status', :if => proc {|x| x.editable? }

  attr_protected :id

  def editable?(user = nil)
    user ||= User.current
    if project
      user.allowed_to?(:edit_easy_web_hooks, project)
    else
      user.allowed_to_globally?(:edit_easy_web_hooks)
    end
  end

  private

  def ensure_attributes
    project = nil if entity_type.constantize.is_a?(Principal)
    author ||= User.current
  end

  def validate_author_with_permission
    unless editable?
      if project
        errors.add(:base, l(:error_no_permission_for_this_project, :project => project.to_s))
      else
        errors.add(:base, l(:error_no_permission))
      end
    end
  end

end

app/controllers/easy_web_hooks_controller.rb
class EasyWebHooksController < ApplicationController

  before_filter :find_optional_project
  before_filter :find_easy_web_hooks, :only => [:index]
  before_filter :find_easy_web_hook, :only => [:edit, :update, :destroy]
  before_filter :authorize
  before_filter :build_new_easy_web_hook, :only => [:new, :create]

  def index
  end

  def new
  end

  def create
    if @easy_web_hook.save
      flash[:notice] = l(:notice_successful_create)

      if params[:continue]
        redirect_to new_easy_web_hook_path(@project)
      else
        redirect_to easy_web_hooks_path(@project)
      end
    else
      render :action => 'new'
    end
  end

  def edit
  end

  def update
    if params[:easy_web_hook].present?
      @easy_web_hook.safe_attributes = params[:easy_web_hook]

      if @easy_web_hook.save
        redirect_to easy_web_hooks_path(@project), :notice => l(:notice_successful_update)
      else
        render :action => 'edit'
      end
    end
  end

  def destroy
    @easy_web_hook.destroy
    redirect_to easy_web_hooks_path(@project), :notice => l(:notice_successful_delete)
  end

  private

  def find_easy_web_hooks
    if @project
      @easy_web_hooks = @project.easy_web_hooks
    else
      @easy_web_hooks = EasyWebHook.where(:project_id => nil).order(:name) || []
      @easy_web_hooks.concat(Project.allowed_to(:view_easy_web_hooks).visible.sorted.
                                     preload(:easy_web_hooks).collect(&:easy_web_hooks).flatten)
    end
  end

  def find_easy_web_hook
    @easy_web_hook = EasyWebHook.find(params[:id]) if params[:id].present?
  rescue ActiveRecord::RecortNotFound
    return render_404
  end

  def build_new_easy_web_hook
    @easy_web_hook = EasyWebHook.new
    @easy_web_hook.safe_attributes = params[:easy_web_hook] if params[:easy_web_hook].present?
    @easy_web_hook.project = @project if @project
    @easy_web_hook.author = User.current
  end

  def authorize
    return render_403 if params[:action].in?(["edit", "update", "destroy"]) && !@easy_web_hook.editable?

    super(params[:controller], params[:action], !@project)
  end

end

app/helpers/easy_web_hooks_helper.rb
module EasyWebHooksHelper

  def entity_type_options_for_select
    EasyWebHook::ENTITY_TYPES.collect do |entity_type|
      entity_label = entity_type == "TimeEntry" ? l(:label_spent_time) : l("label_#{entity_type.downcase}")
      [entity_label, entity_type]
    end
  end

end

app/views/easy_web_hooks/_form.html.erb
<%= error_messages_for "easy_web_hook" %>

<div class="box tabular">
  <% unless @project %>
    <p><%= f.select :project_id, Project.allowed_to(:edit_easy_web_hooks).sorted.collect {|project| [project.to_s, project.id] }, {:include_blank => true}, { :include_blank => true, :label => :field_project } %></p>
  <% end %>

  <p><%= f.text_field :name, :required => true  %></p>

  <p><%= f.select :entity_type, entity_type_options_for_select, {:required => true}, { :include_blank => false } %></p>

  <p><%= f.select :action, EasyWebHook::ENTITY_ACTIONS.collect {|action| [action, action] }, {:required => true}, { :include_blank => false }  %></p>

  <p>
    <%= f.text_field :url, :required => true %>
    <%= content_tag :em, l(:label_easy_web_hooks_url_info), :class => 'info' %>
  </p>

  <p><%= f.select :entity_data_type, EasyWebHook::ENTITY_DATA_TYPES.collect {|data_type| [data_type, data_type] }, { :required => true}, { :include_blank => false } %></p>

  <p><%= f.check_box :status, {:label => :field_active}, EasyWebHook.statuses.invert[1], EasyWebHook.statuses.invert[0] %></p>
</div>

app/views/easy_web_hooks/edit.html.erb
<h2><%= l(:label_easy_web_hook_new) %></h2>

<%= labelled_form_for @easy_web_hook, :url => easy_web_hook_path(@easy_web_hook), :method => 'put' do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>

  <%= f.submit l(:button_save) %>
<% end %>

app/views/easy_web_hooks/index.html.erb
<div class="contextual">
  <% if User.current.can_edit_hooks?(@project) %>
    <%= link_to(l(:label_easy_web_hook_new), new_easy_web_hook_path(@project), :class => 'icon icon-add') %>
  <% end %>
</div>

<h2><%= l(:label_easy_web_hooks) %></h2>

<table class="list">
<tr>
  <% unless @project %>
    <th><%= l(:field_project) %></th>
  <% end %>
  <th><%= l(:field_name) %></th>
  <th><%= l(:field_entity_type) %></th>
  <th><%= l(:field_action) %></th>
  <th><%= l(:field_url) %></th>
  <th><%= l(:field_entity_data_type) %></th>
  <th><%= l(:field_active) %></th>
  <th><%= l(:field_author) %></th>
  <th></th>
</tr>

<% @easy_web_hooks.each_with_index do |easy_web_hook| %>
  <tr class="<%= cycle 'odd', 'even' %>">
    <% if @project.nil? %>
      <td><%= link_to_project(easy_web_hook.project) if easy_web_hook.project %></td>
    <% end %>
    <td>
      <% if easy_web_hook.editable? %>
        <%= link_to easy_web_hook.name, edit_easy_web_hook_path(@project, easy_web_hook) %>
      <% else %>
        <%= easy_web_hook.name %>
      <% end %>
    </td>
    <td><%= easy_web_hook.entity_type %></td>
    <td><%= easy_web_hook.action %></td>
    <td><%= easy_web_hook.url %></td>
    <td><%= easy_web_hook.entity_data_type %></td>
    <td class="tick"><%= checked_image easy_web_hook.active? %></td>
    <td><%= avatar(easy_web_hook.author, :size => "14") %><%= easy_web_hook.author.name %></td>
    <td class="buttons">
      <% if easy_web_hook.editable? %>
        <%= link_to l("button_delete"), easy_web_hook_path(@project, easy_web_hook),
              :method => 'delete', :class => "icon icon-del", :data => { :confirm => l(:text_are_you_sure) } %>
      <% end %>
    </td>
  </tr>
<% end %>

</table>

app/views/easy_web_hooks/new.html.erb
<h2><%= l(:label_easy_web_hook_new) %></h2>

<%= labelled_form_for @easy_web_hook, :url => easy_web_hooks_path(@project) do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>

  <%= f.submit l(:button_create) %>
  <%= f.submit l(:button_create_and_continue), :name => 'continue' %>
<% end %>